use_frameworks!

platform :ios, '8.0'

target 'LejiaScreenFramework_Example' do
  pod 'LejiaScreenFramework', :path => '../'

  target 'LejiaScreenFramework_Tests' do
    inherit! :search_paths

    
  end
end
